cameo/flux_analysis/analysis.py, cameo/strain_design/deterministic/flux_variability_based.py, cameo/visualization/plotting/abstract.py, cameo/visualization/plotting/with_bokeh.py, cameo/visualization/plotting/with_plotly.py
Implemented Line plots in Bokeh and Plotly
=> plot flux scanning based on enforced objective flux results

cameo/models/webmodels.py
Use load_model function to load models @ webmodels module
=> fix: clean imports and use load_model to load all models

cameo/models/webmodels.py
The load_model function was broken. This should fix it. Uminho is still inaccessible though, so I haven’t tested that.
=> Fix load model

tests/test_cobrapy_compatibility.py
cobrapy now uses pytest so the direct import to cameo is not
straight-forward anymore. since this kind of compatiblity won't be
needed in the future I suggest not spending time solving this properly.
=> fix: drop (most) cobrapy tests

cameo/core/pathway.py
Small fix on pathway loading method. It was using cobra.core.Metabolite but it works better with cameo.core.metabolite.
=> fix: use cameo.core.metabolite

cameo/strain_design/heuristic/evolutionary/evaluators.py, cameo/strain_design/heuristic/evolutionary/objective_functions.py, cameo/strain_design/heuristic/evolutionary/optimization.py, cameo/strain_design/heuristic/evolutionary/plotters.py, cameo/strain_design/heuristic/evolutionary/processing.py, cameo/strain_design/heuristic/evolutionary_based.py, tests/test_strain_design_heuristics.py
Highlights:
* Retrieve worst_fitness from objective functions
* Remove is_mo method
* No lists as objective functions
* Fix and improve unit tests
More info:
This solves the problem of is_mo property or checking if there is a list of objectives.
=> Feature: Implement multiobjective function

cameo/core/manipulation.py, cameo/core/target.py, cameo/strain_design/deterministic/flux_variability_based.py, tests/test_targets.py
=> Flux inversion targets

cameo/strain_design/heuristic/evolutionary/optimization.py, tests/test_strain_design_heuristics.py
=> Bug fix: GeneKnockoutOptimization

cameo/strain_design/pathway_prediction/pathway_predictor.py, tests/test_pathway_predictions.py
I fixed the pickling problem when pickling pathway results. And the tests where not running. But I think it is fixed now.
=> Bug fix: pickle pathway predictions

.travis.yml, README.rst, docs/index.rst
https://github.com/Syntaf/travis-sphinx
=> Use travis-sphinx to publish cameo docs to GitHub pages

cameo/api/designer.py, cameo/strain_design/heuristic/evolutionary/optimization.py, cameo/strain_design/heuristic/evolutionary_based.py, tests/test_strain_design_heuristics.py
Also added fix documentation and unit tests.
=> feat: add a time limit to heuristic optimization

cameo/strain_design/pathway_prediction/pathway_predictor.py, cameo/strain_design/pathway_prediction/util.py
Also, refactor to use `model.solver.optimize()`
=> fix: make PathwayPredictor work with custom models

setup.py
Api changed, whilst refactoring, pin gnomic.
=> fix: pin gnomic

cameo/flux_analysis/simulation.py, cameo/util.py, tests/test_flux_analysis.py
The extra variables and constraints were not being consistently removed.
I refactored the problem cache to use cobrapy implementation of context manager.
I extended the unit tests to assure that the extra variables and constraints were properly removed.
BTW: this changes are critical to other projects. Please make release after this is reviewed and merged.
=> Critical bugfix: simulation methods - ROOM, MOMA, lMOMA

cameo/core/target.py, setup.py, tests/test_targets.py
=> fix: gnomic==1.0

cameo/flux_analysis/simulation.py
Update simulation.py to use solution.objective_value vs. legacy solution.f
Tested lightly
=>  Update simulation.py to use solution.objective_value vs. legacy solution.f

cameo/__init__.py, cameo/flux_analysis/analysis.py, cameo/flux_analysis/simulation.py, cameo/flux_analysis/util.py, cameo/strain_design/deterministic/linear_programming.py, cameo/visualization/visualization.py, tests/test_io.py, tests/test_solver_based_model.py, tests/test_targets.py
This should make cameo compatible again with the latest cobrapy release.
=> Fix copbrapy f and x_dict deprecation

cameo/strain_design/deterministic/linear_programming.py
=> Fix optknock bugs

cameo/api/designer.py
We make use of this method in the metabolic-ninja service.
=> refactor: make product translation a public method

cameo/core/strain_design.py, cameo/strain_design/heuristic/evolutionary/variators.py, cameo/strain_design/heuristic/evolutionary_based.py, cameo/visualization/plotting/with_plotly.py
This PR fixes the style errors that are holding up more important work.
=> style: correct new flake8 errors

cameo/strain_design/pathway_prediction/pathway_predictor.py
Address the style comments from the last PR.
=> Fix pathway

cameo/core/target.py, cameo/strain_design/deterministic/flux_variability_based.py
Try to sort out the differential FVA result generation.
=> Fix diff fva result

cameo/flux_analysis/analysis.py
Quick fix to error encountered when running `mass_yield()`.
=> Fix  divison by 0

cameo/strain_design/deterministic/linear_programming.py
Closes #277 
In OptKnock, if the user inputs reactions that are blocked as reactions to exclude, they will be first removed from the model because they are blocked and then raise an error when checking if the reactions to be excluded are in the model.
Filter out blocked reactions from excluded reactions.
=> Fix OptKnock when exluded reactions clash with blocked reactions
